# Generated by Django 4.1.2 on 2022-10-30 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='estate',
            field=models.CharField(default='RJ', max_length=2),
        ),
    ]
